import os

lines = []

lines.append("import 'dart:convert';")
lines.append("import 'dart:math';")
lines.append("import 'dart:typed_data';")
lines.append("import 'dart:ui';")
lines.append("import 'package:http/http.dart' as http;")
lines.append("import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';")
lines.append("import 'package:path_provider/path_provider.dart';")
lines.append("import 'dart:io';")
lines.append("import 'dart:ui' as ui;")
lines.append("")
lines.append("class LoginResult {")
lines.append("  final bool success;")
lines.append("  final String message;")
lines.append("  LoginResult({required this.success, required this.message});")
lines.append("}")
lines.append("")
lines.append("const String _rsaModulusHex =")
lines.append('    "b2867727e19e1163cc084ea57b9fa8406a910c6703413fa7df96c1acdca7b983a262e005af35f9485d92cd4c622eca4a14d6fd818adca5cae73d9d228b4ef05d732b41fb85f80af578a150ebd9a2eb5ececb853372ca4731ca1c8686892987409be3247f9b26cae8e787d8c135fc0652ec0678a5eda0c3d95cc1741517c0c9c3";')
lines.append("const int _rsaExponent = 0x10001;")
lines.append("")
lines.append("final _textRecognizer = TextRecognizer(script: TextRecognitionScript.latin);")
lines.append("")
lines.append("void disposeOCR() {")
lines.append("  _textRecognizer.close();")
lines.append("}")
lines.append("")
lines.append("Future<Map<String, dynamic>> fetchCaptcha(String baseUrl) async {")
lines.append("  final time = DateTime.now().millisecondsSinceEpoch;")
lines.append("  final url = '\/common/image_code.jsp?time=\';")
lines.append("  final resp = await http.get(")
lines.append("    Uri.parse(url),")
lines.append("    headers: {")
lines.append("      'User-Agent': 'Mozilla/5.0 (Linux; Android 13; Mobile) AppleWebKit/537.36 Chrome/120.0.0.0 Mobile Safari/537.36',")
lines.append("    },")
lines.append("  ).timeout(const Duration(seconds: 5));")
lines.append("  String cookie = '';")
lines.append("  final setCookie = resp.headers['set-cookie'];")
lines.append("  if (setCookie != null) cookie = setCookie.split(';')[0];")
lines.append("  return {'cookie': cookie, 'bytes': resp.bodyBytes};")
lines.append("}")
lines.append("")
lines.append("Future<Uint8List> preprocessCaptcha(Uint8List bytes) async {")
lines.append("  try {")
lines.append("    final codec = await instantiateImageCodec(bytes);")
lines.append("    final frame = await codec.getNextFrame();")
lines.append("    final image = frame.image;")
lines.append("    const scale = 3;")
lines.append("    final newWidth = image.width * scale;")
lines.append("    final newHeight = image.height * scale;")
lines.append("    final recorder = ui.PictureRecorder();")
lines.append("    final canvas = Canvas(recorder);")
lines.append("    canvas.drawImageRect(")
lines.append("      image,")
lines.append("      Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()),")
lines.append("      Rect.fromLTWH(0, 0, newWidth.toDouble(), newHeight.toDouble()),")
lines.append("      Paint()..filterQuality = FilterQuality.high,")
lines.append("    );")
lines.append("    final pic = recorder.endRecording();")
lines.append("    final scaledImage = await pic.toImage(newWidth, newHeight);")
lines.append("    final byteData = await scaledImage.toByteData(format: ImageByteFormat.png);")
lines.append("    image.dispose();")
lines.append("    scaledImage.dispose();")
lines.append("    return byteData!.buffer.asUint8List();")
lines.append("  } catch (e) {")
lines.append("    return bytes;")
lines.append("  }")
lines.append("}")
lines.append("")
lines.append("Future<String> recognizeCaptcha(Uint8List imageBytes) async {")
lines.append("  final processed = await preprocessCaptcha(imageBytes);")
lines.append("  final tempDir = await getTemporaryDirectory();")
lines.append("  final file = File('\/captcha_\.png');")
lines.append("  await file.writeAsBytes(processed);")
lines.append("  try {")
lines.append("    final inputImage = InputImage.fromFilePath(file.path);")
lines.append("    final recognized = await _textRecognizer.processImage(inputImage);")
lines.append("    var text = recognized.text.trim();")
lines.append("    text = text.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '').toUpperCase();")
lines.append("    if (text.length > 6) text = text.substring(0, 4);")
lines.append("    return text;")
lines.append("  } catch (e) {")
lines.append("    return '';")
lines.append("  } finally {")
lines.append("    try { await file.delete(); } catch (_) {}")
lines.append("  }")
lines.append("}")
lines.append("")
lines.append("String _rsaEncrypt(String plaintext) {")
lines.append("  final plainBytes = utf8.encode(plaintext);")
lines.append("  final n = BigInt.parse(_rsaModulusHex, radix: 16);")
lines.append("  final e = BigInt.from(_rsaExponent);")
lines.append("  final modLen = (n.bitLength + 7) >> 3;")
lines.append("  final padLen = modLen - plainBytes.length - 3;")
lines.append("  if (padLen < 8) throw Exception('plaintext too long');")
lines.append("  final random = Random.secure();")
lines.append("  final padding = <int>[];")
lines.append("  while (padding.length < padLen) {")
lines.append("    final b = random.nextInt(255) + 1;")
lines.append("    padding.add(b);")
lines.append("  }")
lines.append("  final padded = <int>[0x00, 0x02, ...padding, 0x00, ...plainBytes];")
lines.append("  final m = _bytesToBigInt(Uint8List.fromList(padded));")
lines.append("  final c = m.modPow(e, n);")
lines.append("  var result = c.toRadixString(16);")
lines.append("  result = result.padLeft(modLen * 2, '0');")
lines.append("  return result;")
lines.append("}")
lines.append("")
lines.append("BigInt _bytesToBigInt(Uint8List bytes) {")
lines.append("  BigInt result = BigInt.zero;")
lines.append("  for (final b in bytes) {")
lines.append("    result = (result << 8) | BigInt.from(b);")
lines.append("  }")
lines.append("  return result;")
lines.append("}")
lines.append("")
lines.append("String generateLoginKey(String username, String password, String captcha) {")
lines.append('  final plain = \'{"userName":"\","password":"\","rand":"\"}\';')
lines.append("  return _rsaEncrypt(plain);")
lines.append("}")
lines.append("")
lines.append("Future<LoginResult> doPortalLogin({")
lines.append("  required String baseUrl,")
lines.append("  required String loginKey,")
lines.append("  required String cookie,")
lines.append("  String wlanuserip = '',")
lines.append("  String wlanacip = '',")
lines.append("  Duration timeout = const Duration(seconds: 5),")
lines.append("}) async {")
lines.append("  final url = '\/ajax/login';")
lines.append("  final body = <String, String>{")
lines.append("    'loginKey': loginKey,")
lines.append("    'wlanuserip': wlanuserip,")
lines.append("    'wlanacip': wlanacip,")
lines.append("  };")
lines.append("  try {")
lines.append("    final response = await http")
lines.append("        .post(")
lines.append("          Uri.parse(url),")
lines.append("          body: body,")
lines.append("          headers: {")
lines.append("            'User-Agent': 'Mozilla/5.0 (Linux; Android 13; Mobile) AppleWebKit/537.36 Chrome/120.0.0.0 Mobile Safari/537.36',")
lines.append("            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',")
lines.append("            'Cookie': cookie,")
lines.append("            'Referer': '\/qs/',")
lines.append("            'Origin': baseUrl,")
lines.append("            'Accept': 'application/json, text/javascript, */*; q=0.01',")
lines.append("          },")
lines.append("        )")
lines.append("        .timeout(timeout);")
lines.append("    final raw = utf8.decode(response.bodyBytes);")
lines.append("    bool success = false;")
lines.append("    String message = '';")
lines.append("    try {")
lines.append("      final result = jsonDecode(raw) as Map<String, dynamic>;")
lines.append("      final code = result['resultCode']?.toString() ?? '';")
lines.append("      if (code == '0' || code == '13002000') success = true;")
lines.append("      message = (result['resultInfo'] ?? result['resultCode'] ?? '').toString();")
lines.append("    } catch (_) {")
lines.append("      message = 'bad response';")
lines.append("    }")
lines.append("    return LoginResult(success: success, message: message);")
lines.append("  } catch (e) {")
lines.append("    return LoginResult(success: false, message: 'error: \');")
lines.append("  }")
lines.append("}")
lines.append("")
lines.append("Future<LoginResult> autoLogin({")
lines.append("  required String baseUrl,")
lines.append("  required String username,")
lines.append("  required String password,")
lines.append("  int maxRetries = 8,")
lines.append("}) async {")
lines.append("  String lastMsg = '';")
lines.append("  for (int i = 0; i < maxRetries; i++) {")
lines.append("    try {")
lines.append("      final captchaData = await fetchCaptcha(baseUrl);")
lines.append("      final cookie = captchaData['cookie'] ?? '';")
lines.append("      final bytes = captchaData['bytes'] as Uint8List?;")
lines.append("      if (bytes == null || cookie.isEmpty) {")
lines.append("        await Future.delayed(const Duration(seconds: 1));")
lines.append("        continue;")
lines.append("      }")
lines.append("      final captcha = await recognizeCaptcha(bytes);")
lines.append("      if (captcha.length < 3) continue;")
lines.append("      final loginKey = generateLoginKey(username, password, captcha);")
lines.append("      final result = await doPortalLogin(")
lines.append("        baseUrl: baseUrl,")
lines.append("        loginKey: loginKey,")
lines.append("        cookie: cookie,")
lines.append("      );")
lines.append("      if (result.success) return result;")
lines.append("      lastMsg = result.message;")
lines.append("      await Future.delayed(const Duration(milliseconds: 800));")
lines.append("    } catch (e) {")
lines.append("      lastMsg = e.toString().split('\\n').first;")
lines.append("      await Future.delayed(const Duration(seconds: 1));")
lines.append("    }")
lines.append("  }")
lines.append("  return LoginResult(success: false, message: '重试 \ 次失败, 最后: \');")
lines.append("}")
lines.append("")
lines.append("Future<bool> isOnline({Duration timeout = const Duration(seconds: 4)}) async {")
lines.append("  try {")
lines.append("    final response = await http.get(Uri.parse('http://www.baidu.com')).timeout(timeout);")
lines.append("    final body = utf8.decode(response.bodyBytes);")
lines.append("    return body.toLowerCase().contains('baidu') && !body.toLowerCase().contains('enet.10000');")
lines.append("  } catch (_) {")
lines.append("    return false;")
lines.append("  }")
lines.append("}")

content = '\n'.join(lines) + '\n'

# 修复 char(10) -> \n
content = content.replace("split(char(10))", "split('\\\\n')")

with open('lib/portal_login.dart', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

print('portal_login.dart rewritten')
print('Size:', len(content))
print('Has preprocessCaptcha:', 'preprocessCaptcha' in content)
print('Has 8 retries:', 'maxRetries = 8' in content)
print('Has Origin header:', 'Origin' in content)
